name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
            python3-pip git zip unzip openjdk-11-jdk
          pip install buildozer cython==0.29.36

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FuturePointSubmitter.apk
          path: bin/*.apk
