name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
            python3-pip git zip unzip openjdk-11-jdk
          pip install cython==0.29.36 buildozer

      - name: Set Android SDK Environment
        run: |
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FuturePointSubmitter.apk
          path: bin/*.apk
